[project]
name = "CV"

[dependencies]
AsioHeaders = "*"
BH = "*"
DBI = "*"
Matrix = "*"
NLP = "*"
"R.cache" = "*"
"R.methodsS3" = "*"
"R.oo" = "*"
"R.utils" = "*"
R6 = "*"
RColorBrewer = "*"
Rcpp = "*"
RefManageR = "*"
S7 = "*"
anytime = "*"
askpass = "*"
backports = "*"
base64enc = "*"
base64url = "*"
bibtex = "*"
bit = "*"
bit64 = "*"
blob = "*"
brew = "*"
broom = "*"
bslib = "*"
cachem = "*"
callr = "*"
cellranger = "*"
cli = "*"
clipr = "*"
codetools = "*"
collections = "*"
commonmark = "*"
conflicted = "*"
cpp11 = "*"
cranlogs = "*"
crayon = "*"
curl = "*"
"data.table" = "*"
dbplyr = "*"
desc = "*"
digest = "*"
dplyr = "*"
dtplyr = "*"
evaluate = "*"
farver = "*"
fastmap = "*"
fontawesome = "*"
forcats = "*"
fs = "*"
fuzzyjoin = "*"
gargle = "*"
gcite = "*"
generics = "*"
geosphere = "*"
ggplot2 = "*"
gh = "*"
gitcreds = "*"
glue = "*"
googledrive = "*"
googlesheets4 = "*"
gtable = "*"
haven = "*"
highr = "*"
hms = "*"
htmltools = "*"
httpgd = "*"
httr = "*"
httr2 = "*"
ids = "*"
igraph = "*"
ini = "*"
isoband = "*"
jquerylib = "*"
jsonlite = "*"
knitr = "*"
labeling = "*"
languageserver = "*"
later = "*"
lattice = "*"
lifecycle = "*"
lintr = "*"
lubridate = "*"
magrittr = "*"
memoise = "*"
mime = "*"
modelr = "*"
openssl = "*"
pbapply = "*"
pillar = "*"
pkgbuild = "*"
pkgconfig = "*"
pkgload = "*"
pkgsearch = "*"
plyr = "*"
prettyunits = "*"
processx = "*"
progress = "*"
ps = "*"
purrr = "*"
quarto = "*"
ragg = "*"
rappdirs = "*"
readr = "*"
readxl = "*"
rematch = "*"
rematch2 = "*"
renv = "*"
reprex = "*"
rex = "*"
rlang = "*"
rmarkdown = "*"
roxygen2 = "*"
rprojroot = "*"
rstudioapi = "*"
rvest = "*"
sass = "*"
scales = "*"
secretbase = "*"
selectr = "*"
slam = "*"
stringdist = "*"
stringi = "*"
stringr = "*"
styler = "*"
sys = "*"
systemfonts = "*"
tarchetypes = "*"
targets = "*"
textshaping = "*"
tibble = "*"
tidyr = "*"
tidyselect = "*"
tidyverse = "*"
timechange = "*"
tinytex = "*"
tm = "*"
tsibble = "*"
tzdb = "*"
unigd = "*"
utf8 = "*"
uuid = "*"
vctrs = "*"
versions = "*"
viridisLite = "*"
vitae = "*"
vroom = "*"
withr = "*"
wordcloud = "*"
xfun = "*"
xml2 = "*"
xmlparsedata = "*"
xtable = "*"
yaml = "*"

[dependencies.pkgmeta]
git = "robjhyndman/pkgmeta"
rev = "6ed051c473f81ab9497ce159302ac94e62b4d954"

