---
name: Rob J Hyndman
address: "Department of Econometrics & Business Statistics,\\tabularnewline Monash University, VIC 3800, Australia."
www: robjhyndman.com
phone: +61 3 9905 5141
email: "Rob.Hyndman@monash.edu"
twitter: robjhyndman
github: robjhyndman
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000088"
csl: numeric-apa-cv.csl
keep_md: yes
output:
  vitae::hyndman:
    keep_tex: yes
header-includes:
  \lhead{\sf\textcolor[gray]{0.4}{Publications : \@name}}
---

\newcounter{bib}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)
library(tidyverse)
library(RefManageR)
library(vitae)
source("functions.R")
```

```{r Rpackages, eval=FALSE}
# Find installed or CRAN packages with Hyndman as an author
rjhpkgs <- find_rjh_packages()
# Remove some works in progress or not suitable for CV
rjhpkgs <- rjhpkgs[!(rjhpkgs %in% c("indmortality2","informs"))]
# Write bib file
write_packages_bib(rjhpkgs, file="Rpackages.bib")
```

```{r bibfiles}
# Read any bib files
pubs <- bibliography_entries("rjhpubs.bib")
reports <- bibliography_entries("rjhreports.bib")
packages <- bibliography_entries("Rpackages.bib")
```


# Rob J Hyndman: Publications List

```{r publist}
# Find editorials
editorials <- c(
  "hyndman2015new",
  "hyndman2015change",
  "IJFeditorial13",
  "tourismeditorial11",
  "IJFeditorial10b",
  "IJFeditorial10a",
  "IJFeditorial06",
  "IJFeditorial05"
)
```

## Books

```{r books}
pubs %>%
  filter(bibtype == "Book") %>%
  arrange(year, surnames)
```

## Scholarly book chapters

```{r book-chapters}
pubs %>%
  filter(bibtype %in% c("InBook", "InCollection")) %>%
  arrange(year, surnames)
```


## Refereed journal articles

```{r research-papers}
# Normal articles excluding editorials
pubs %>%
  filter(bibtype == "Article", !(key %in% editorials)) %>%
  arrange(year, surnames)
```

## Refereed conference proceedings

```{r papers-in-proceedings}
pubs %>%
  filter(bibtype == "InProceedings") %>%
  arrange(year, surnames)
```

